[package]
name = "rust-book-examples"
version = "0.1.0"
authors = ["Brandon DeRosier <bdero@mit.edu>"]

[dependencies]
rand = "*"

[[bin]]
name = "guessing_game"
path = "src/learn-rust/guessing-game.rs"

[[bin]]
name = "dining-philosophers"
path = "src/learn-rust/dining-philosophers.rs"
